### ISSUE TITLE
Dark mode is not reflected on charts inside Dashboard view

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/starters#45]
A V23 starter downloaded from start.vaadin.com with a Dashboard view and Dark mode doesn't properly show the charts in Dark mode (even though they appear properly in the preview):

![image](https://user-images.githubusercontent.com/42799254/152964253-85a9df59-cbf1-4d03-b120-880f76c27ae0.png)

**Comment by rolfsmeds** [comment]
Actually the problem seems to be that the new charts theme, is not loading at all. Instead the chart is rendered with the old theme, which has no dark mode.

This is how the chart renders with the new theme in light mode in start.vaadin.com
<img width="957" alt="image" src="https://user-images.githubusercontent.com/4611559/158345436-3f00abba-c867-43b2-9703-e6ff80e0bca3.png">
